/*
 * ===============================LICENSE_START======================================
 *  dcae-analytics
 * ================================================================================
 *    Copyright © 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  ============================LICENSE_END===========================================
 */

package org.openecomp.dcae.apod.analytics.model.facade.tca;

import lombok.Data;

/**
 * Response generated by TCA for VES Message
 *
 * @author Rajiv Singla . Creation Date: 11/9/2016.
 */
@Data
public class TCAVESResponse implements TCAFacadeModel {

    private static final long serialVersionUID = 1L;

    /**
     * Closed loop control name for response.
     *
     * @param closedLoopControlName Closed loop control name
     * @return Closed loop control name
     */
    private String closedLoopControlName;

    /**
     * Version of response generated by TCA.
     *
     * @param version new version
     * @return Version of response
     */
    private String version;

    /**
     * Request identifier.
     *
     * @param requestID request id
     * @return request id
     */
    private String requestID;

    /**
     * Timestamp for closed loop alarm start.
     *
     * @param closedLoopAlarmStart Timestamp for closed loop alarm
     * @return Timestamp for closed loop alarm.
     */
    private Long closedLoopAlarmStart;

    /**
     * Client for closed loop event.
     *
     * @param closedLoopEventClient Client for closed loop event
     * @return Client for closed loop event
     */
    private String closedLoopEventClient;

    /**
     * Target type.
     *
     * @param targetType target type
     * @return target type
     */
    private String targetType;

    /**
     * AAI
     *
     * @param aai AAI
     * @return aai
     */
    private AAI aai;

    /**
     * Target for response.
     *
     * @param target target
     * @return target
     */
    private String target;

    private String from;

    /**
     * Policy scope.
     *
     * @param policyScope new Policy scope
     * @return Policy scope
     */
    private String policyScope;

    /**
     * Policy name.
     *
     * @param policyName Policy name
     * @return Policy name
     */
    private String policyName;

    /**
     * Policy version.
     *
     * @param policyVersion policy version
     * @return Policy version
     */
    private String policyVersion;

    /**
     * Closed loop event's status.
     *
     * @param closedLoopEventStatus closed loop event status
     * @return closedLoopEventStatus
     */
    private String closedLoopEventStatus;
}
