/*
 * ===============================LICENSE_START======================================
 *  dcae-analytics
 * ================================================================================
 *    Copyright © 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  ============================LICENSE_END===========================================
 */

package org.openecomp.dcae.apod.analytics.model.facade.tca;

import lombok.Data;

/**
 * Response generated by TCA for VES Message
 *
 * @author Rajiv Singla . Creation Date: 11/9/2016.
 */
@Data
public class TCAVESResponse implements TCAFacadeModel {

    private static final long serialVersionUID = 1L;

    /**
     * Closed loop control name for response.
     */
    private String closedLoopControlName;

    /**
     * Version of response generated by TCA.
     */
    private String version;

    /**
     * Request identifier.
     */
    private String requestID;

    /**
     * Timestamp for closed loop alarm start.
     */
    private Long closedLoopAlarmStart;

    /**
     * Client for closed loop event.
     */
    private String closedLoopEventClient;

    /**
     * Target type.
     */
    private String targetType;

    /**
     * AAI
     */
    private AAI aai;

    /**
     * Target for response.
     */
    private String target;

    /**
     *
     */
    private String from;

    /**
     * Policy scope.
     */
    private String policyScope;

    /**
     * Policy name.
     */
    private String policyName;

    /**
     * Policy version.
     */
    private String policyVersion;

    /**
     * Closed loop event's status.
     */
    private String closedLoopEventStatus;
}
